CREATE TABLE [fifa19] (
       iden integer not null primary key
      ,ID integer
      ,Name text
      ,Age integer
      ,Photo text
      ,Nationality text
      ,Flag text
      ,Overall integer
      ,Potential integer
      ,Club text
      ,Club_Logo text
      ,Value integer
      ,Wage integer
      ,Special integer
      ,Preferred_Foot text
      ,International_Reputation integer
      ,Weak_Foot integer
      ,Skill_Moves integer
      ,Work_Rate text
      ,Body_type text
      ,Real_Face text
      ,Position text
      ,Jersey_Number integer
      ,Joined date
      ,Loaned_From text
      ,Contract_Valid_Until text
      ,Height text
      ,Weight text
      ,LS text
      ,ST text
      ,RS text
      ,LW text
      ,LF text
      ,CF text
      ,RF text
      ,RW text
      ,LAM text
      ,CAM text
      ,RAM text
      ,LM text
      ,LCM text
      ,CM text
      ,RCM text
      ,RM text
      ,LWB text
      ,LDM text
      ,CDM text
      ,RDM text
      ,RWB text
      ,LB text
      ,LCB text
      ,CB text
      ,RCB text
      ,RB text
      ,Crossing integer
      ,Finishing integer
      ,HeadingAccuracy integer
      ,ShortPassing integer
      ,Volleys integer
      ,Dribbling integer
      ,Curve integer
      ,FKAccuracy integer
      ,LongPassing integer
      ,BallControl integer
      ,Acceleration integer
      ,SprintSpeed integer
      ,Agility integer
      ,Reactions integer
      ,Balance integer
      ,ShotPower integer
      ,Jumping integer
      ,Stamina integer
      ,Strength integer
      ,LongShots integer
      ,Aggression integer
      ,Interceptions integer
      ,Positioning integer
      ,Vision integer
      ,Penalties integer
      ,Composure integer
      ,Marking integer
      ,StandingTackle integer
      ,SlidingTackle integer
      ,GKDiving integer
      ,GKHandling integer
      ,GKKicking integer
      ,GKPositioning integer
      ,GKReflexes integer
      ,Release_Clause text
)